// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require("Verifier");
const proof = require("../../zokrates/code/square/proof.json");

// - use the contents from proof.json generated from zokrates steps

contract("Verifier", function (accounts) {
  describe("verfier", function () {
    beforeEach(async function () {
      this.contract = await SquareVerifier.new(accounts);
    });
    // Test verification with correct proof
    it("Test verification with correct proof", async function () {
      let result = await this.contract.verifyTx.call(proof.proof, proof.inputs);
      assert.equal(result, true, "Verification failed");
    });

    // Test verification with incorrect proof
    it("Test verification with incorrect proof", async function () {
      let result = await this.contract.verifyTx.call(proof.proof, [
        "0x0000000000000000000000000000000000000000000000000000000000000008",
      ]);
      assert.equal(result, false, "Verification succeeded");
    });
  });
});
